[phases.setup]
nixPkgs = ["python311", "ffmpeg", "imagemagick"]
aptPkgs = ["ffmpeg", "imagemagick"]

[phases.build]
cmds = [
  "sed -i 's/rights=\"none\" pattern=\"@\\*\"/rights=\"read|write\" pattern=\"@*\"/' /etc/ImageMagick-6/policy.xml || true"
]

[start]
cmd = "python main.py"
